builds:
  - binary: mackerel-plugin-linux-process-status
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
     - -X main.Version={{.Version}}
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: kazeburo
    name: mackerel-plugin-linux-process-status
